// Блок параметров для настройки запуска
properties([
    parameters([
        // Параметр для указания тегов тестов
        string(name: 'TAGS',
               defaultValue: 'smoke',
               description: 'Test tags to run: smoke, regress, api, etc.')
    ])
])

pipeline {
  agent any
  options { skipDefaultCheckout(true) }

  parameters {
    string(name: 'TAGS', defaultValue: 'smoke', description: 'smoke, regress, etc')
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
        sh 'chmod +x gradlew'
      }
    }

    stage('Run Tests') {
      steps {
        sh "./gradlew clean test --info --stacktrace -Ptags=${params.TAGS}"
      }
    }
  }

  post {
    always {
      allure includeProperties: false,
             results: [[path: 'build/allure-results']]
    }
  }
}
